//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace Msdk
{
		public class TokenRet
		{
			public int type = 0;
			public string value = "";
			public long expiration = 0;
			
            public int Type 
            { 
                get{return type;} 
                set{ type = value;}
            }
            public string Value 
            { 
                get{return value;} 
                set{  this.value = value;}
            }
            public string Expiration
            { 
                get{return expiration.ToString();} 
                set{  expiration = long.Parse(value);}
            }
			public TokenRet() {
				
			}
			
			public TokenRet(int type, string value, long expiration) : base(){				
				this.type = type;
				this.value = value;
				this.expiration = expiration;
			}
		}
}

